exports.up = knex => knex.schema.createTable('notas_tbl_knex', table => {
    table.increments('id').unique().notNullable()

    table.string('destinatario', [100])
    table.string('cnpj_destinatario', [50])
    table.string('nome_pj_emitente', [100])
    table.string('chavedeacesso', [100])
    table.date('data_emissao', [50])
    table.date('data_entrada', [50])
    table.string('numero', [50])
    table.string('uf_origem', [50])
    table.string('uf_destino', [50])
    table.string('codigo_item', [50])
    table.string('descriçao_item', [255])
    table.string('ean', [50])
    table.string('ncm', [50])
    table.string('cest', [50])
    table.string('cfop', [50])
    table.string('unidade', [50])
    table.string('quantidade', [50])
    table.string('valor_unit', [50])
    table.string('valor_bruto', [50])
    table.string('valor_desconto', [50])
    table.string('valor_frete', [50])
    table.string('valor_seguro', [50])
    table.string('valor_outras_despesas', [50])
    table.string('valor_ipi', [50])
    table.string('base_icms', [50])
    table.string('aliq_icms', [50])
    table.string('valor_icms', [50])
    table.string('base_icmsst', [50])
    table.string('valor_icmsst', [50])
    table.string('aliq_icmsst', [50])
    table.string('aliq_icmssn', [50])
    table.string('valor_icmssn', [50])
    table.string('base_icmsst_retido', [50])
    table.string('valor_icmsst_retido', [50])
    table.string('mva_7', [50])
    table.string('mva_12', [50])
    table.string('tipo_antecipado', [50])
    table.string('origem', [50])
    table.string('pendente', [50]).defaultTo('0')
    table.string('escritorio', [50])
    table.string('inserido', [50])
    table.timestamp('modificado').notNullable().defaultTo(knex.fn.now())
    table.string('usuario', [50])
    table.date('data_entrada_bkp', [50])
    table.string('diferencial_de_aliquota', [50]).defaultTo('NÃO')
    table.string('nf_devolvida', [50]).defaultTo('NÃO')


    table.timestamp('created_at').defaultTo(knex.fn.now())
    table.timestamp('updated_at').defaultTo(knex.fn.now())


});

exports.down = knex => knex.schema.dropTable('produtos_tbl_knex');

